# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'EC2 Instance'
    sourceFolder: 'Research'
    contents: '**'
    targetFolder: '/home/ubuntu/repoTemp'
    cleanTargetFolder: true
    readyTimeout: '20000'
- task: SSH@0
  inputs:
    sshEndpoint: 'EC2 Instance'
    runOptions: 'commands'
    commands: |
      find /home/aj/project/server -maxdepth 1 -type f -delete
      sudo rm /home/aj/project/documentRoot/*
      sudo mv  -v /home/ubuntu/repoTemp/* /home/aj/project
      sudo service project-server stop
      sudo service project-server start
    readyTimeout: '20000'
